name: CI

on:
  pull_request:
    branches: [ main ]

jobs:
  job-install:
    name: Install
    runs-on: ubuntu-latest

    steps:
      - name: Checkout current commit (${{ github.sha }})
        uses: actions/checkout@v3

      - name: Caching dependencies
        id: cache-dependencies
        uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ runner.OS }}-build-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.OS }}-build-
      - name: Install Dependencies
        if: steps.cache-dependencies.output.cache-hit != 'true'
        run: npm install

#      - name: Run Lint
#        run: npm run lint

      - name: Run Test
        run: npx jest --ci --json --coverage --testLocationInResults --outputFile=report.json

      - uses: ArtiomTr/jest-coverage-report-action@v2
        with:
          coverage-file: report.json
          base-coverage-file: report.json
