name: Test CI

on:
  pull_request:
    branches: 
    - main

jobs:
  job-install:
    name: Install
    runs-on: ubuntu-latest

    steps:
      - name: Checkout current commit (${{ github.sha }})
        uses: actions/checkout@v3
        with:
          ref: "develop"
        run: npm run test:ci

