name: TEST CI

on:
  pull_request:
    branches:
      - main

jobs:
  job-install:
    name: Install dependencies
    runs-on: ubuntu-latest

    steps:
      - name: Checkout current commit (${{ github.sha }})
        uses: actions/checkout@v3
        run: npm test:ci

      - uses: ArtiomTr/jest-coverage-report-action@v2
        with:
          coverage-file: report.json
          base-coverage-file: report.json
