name: TEST CI

on:
  pull_request:
    branches:
      - main

jobs:
  job-install:
    name: run test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout current commit (${{ github.sha }})
        uses: actions/checkout@v3

      - name: Run TEST
        run: npm run test:ci
